name: build binary file

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -alh
#       - run: npm install
#         working-directory: ./websockify
#       - run: npm install -g pkg
#         working-directory: ./websockify
#       - run: pkg -t node14-linux-arm64 package.json
#         working-directory: ./websockify

#       - name: Deploy
#         uses: s0/git-publish-subdir-action@develop
#         env:
#           REPO: self
#           BRANCH: build
#           FOLDER: websockify
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
